/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica4;

/**
 *
 * @author esp15
 */
public class Planilla extends javax.swing.JFrame {
    
    Trabajador[] personal = new Trabajador[10];
    int num;
    /**
     * Creates new form Planilla
     */
    public Planilla() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Empleados en Planilla");
        empleadoBoton.setSelected(true);
        num = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        agregarBoton = new javax.swing.JButton();
        mostrarBotón = new javax.swing.JButton();
        buscarBotón = new javax.swing.JButton();
        bonificacionTexto = new javax.swing.JTextField();
        codigoTexto = new javax.swing.JTextField();
        nombreTexto = new javax.swing.JTextField();
        basicoTexto = new javax.swing.JTextField();
        diasFaltaTexto = new javax.swing.JTextField();
        horasExtraTexto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        empleadoBoton = new javax.swing.JRadioButton();
        consultorBoton = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Empresa SA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 50));

        agregarBoton.setText("agregar");
        agregarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBotonActionPerformed(evt);
            }
        });
        jPanel1.add(agregarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        mostrarBotón.setText("mostrar");
        mostrarBotón.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarBotónActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarBotón, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));

        buscarBotón.setText("buscar");
        buscarBotón.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBotónActionPerformed(evt);
            }
        });
        jPanel1.add(buscarBotón, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, -1));
        jPanel1.add(bonificacionTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 230, -1));

        codigoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTextoActionPerformed(evt);
            }
        });
        jPanel1.add(codigoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 230, -1));
        jPanel1.add(nombreTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 230, -1));
        jPanel1.add(basicoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 230, -1));
        jPanel1.add(diasFaltaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 230, -1));
        jPanel1.add(horasExtraTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 230, -1));

        jLabel2.setText("Bonificacion Extra");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jLabel3.setText("Codigo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel5.setText("S_Basico");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel6.setText("Dias de Falta");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel7.setText("Horas Extra");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        empleadoBoton.setText("empleado");
        empleadoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadoBotonActionPerformed(evt);
            }
        });
        jPanel1.add(empleadoBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, -1));

        consultorBoton.setText("consultor");
        consultorBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultorBotonActionPerformed(evt);
            }
        });
        jPanel1.add(consultorBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, -1));

        jMenu1.setText("File");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mostrarBotónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarBotónActionPerformed
        String cadena = "";
        for(int i=0; i<personal.length; i++){
            if(personal[i] != null){
                cadena = cadena + 
                        "Codigo: " + personal[i].getCodigo() + 
                        "\nNombre: " + personal[i].getNombre() + 
                        "\nBasico: " + personal[i].getBasico() + 
                        "\nRetenciones: " + personal[i].getRetenciones();
                if(personal[i] instanceof Empleado){
                    cadena = cadena +  "\nDias: " + ((Empleado) personal[i]).getDiasFaltas();
                }else{
                    cadena = cadena + "\nBonificacion: " +  ((Consultor) personal[i]).getBonificacion();
                }
                cadena = cadena + "\nNeto: " + personal[i].getNeto() + "\n\n";
            }
        }
        System.out.println(cadena);
    }//GEN-LAST:event_mostrarBotónActionPerformed

    private void codigoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTextoActionPerformed

    private void consultorBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultorBotonActionPerformed
        if(empleadoBoton.isSelected()){
            empleadoBoton.setSelected(false);
            consultorBoton.setSelected(true);
        }
    }//GEN-LAST:event_consultorBotonActionPerformed

    private void agregarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBotonActionPerformed
        num++;
        try {
            if (num > personal.length) {
                throw new RangoException("Arreglo lleno");
            }else{
                if(empleadoBoton.isSelected()){
                    personal[num] = new Empleado(
                            Integer.parseInt(codigoTexto.getText()), 
                            nombreTexto.getText(), 
                            Integer.parseInt(basicoTexto.getText()),
                            Integer.parseInt(diasFaltaTexto.getText()),
                            Integer.parseInt(horasExtraTexto.getText())
                    );
                }else{
                    personal[num] = new Consultor(Integer.parseInt(codigoTexto.getText()), 
                            nombreTexto.getText(), 
                            Integer.parseInt(basicoTexto.getText()),
                            Integer.parseInt(bonificacionTexto.getText())
                    );
                }
                personal[num].calcularRetenciones(0.21);
                personal[num].calcularNeto(num);
            }
        } catch (RangoException rangoException) {
            rangoException.mostrar();
        }
        
    }//GEN-LAST:event_agregarBotonActionPerformed

    private void buscarBotónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBotónActionPerformed
        var codigo = Integer.parseInt(codigoTexto.getText());
        var i = 1;
        var encontrado = false;
        String mensaje;
        while(i<personal.length && !encontrado){
            if(codigo != personal[i].getCodigo()){
                i++;
            }else{
                encontrado = true;
            }
        }
        if(encontrado){
            mensaje = "Codigo: " + personal[i].getCodigo() + 
                    "\nNombre: " + personal[i].getNombre() + 
                    "\nBasico: " + personal[i].getBasico() + 
                    "\nRetenciones: " + personal[i].getRetenciones() + 
                    "\nNeto: " + personal[i].getNeto() + "\n\n";
        }else{
            mensaje = "No se encuentra";
        }
        System.out.println(mensaje);
    }//GEN-LAST:event_buscarBotónActionPerformed

    private void empleadoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadoBotonActionPerformed
        if(consultorBoton.isSelected()){
            consultorBoton.setSelected(false);
            empleadoBoton.setSelected(true);
        }
    }//GEN-LAST:event_empleadoBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Planilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Planilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBoton;
    private javax.swing.JTextField basicoTexto;
    private javax.swing.JTextField bonificacionTexto;
    private javax.swing.JButton buscarBotón;
    private javax.swing.JTextField codigoTexto;
    private javax.swing.JRadioButton consultorBoton;
    private javax.swing.JTextField diasFaltaTexto;
    private javax.swing.JRadioButton empleadoBoton;
    private javax.swing.JTextField horasExtraTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mostrarBotón;
    private javax.swing.JTextField nombreTexto;
    // End of variables declaration//GEN-END:variables
}
